[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --headed --browser chromium --trace --alluredir=reports/allure-results -v
markers =
    sanity: Sanity test markers
    ui: UI component tests
    datepicker: Date picker tests
    upload: File upload tests
    dragdrop: Drag and drop tests
    keyboard: Keyboard interaction tests
    mouse: Mouse action tests

